In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [3]:
data = pd.read_csv('iris.csv')
data.head(10)
data.shape

(150, 5)

In [4]:
X = data.drop('Name', axis=1)
y = data['Name']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

LogisticRegression()

In [28]:
predicted = logr.predict([[5.0,3.6,1.4,0.2]])
print(predicted)

['Iris-setosa']


C:\Users\MGM\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [7]:
y_pred = logr.predict(X_test)
print(X_test,y_pred )

     SepalLength  SepalWidth  PetalLength  PetalWidth
139          6.9         3.1          5.4         2.1
49           5.0         3.3          1.4         0.2
17           5.1         3.5          1.4         0.3
147          6.5         3.0          5.2         2.0
124          6.7         3.3          5.7         2.1
114          5.8         2.8          5.1         2.4
52           6.9         3.1          4.9         1.5
50           7.0         3.2          4.7         1.4
89           5.5         2.5          4.0         1.3
123          6.3         2.7          4.9         1.8
109          7.2         3.6          6.1         2.5
104          6.5         3.0          5.8         2.2
130          7.4         2.8          6.1         1.9
66           5.6         3.0          4.5         1.5
77           6.7         3.0          5.0         1.7
46           5.1         3.8          1.6         0.2
90           5.5         2.6          4.4         1.2
68           6.2         2.2

In [8]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 7  0  0]
 [ 0  9  1]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      0.90      0.95        10
 Iris-virginica       0.93      1.00      0.96        13

       accuracy                           0.97        30
      macro avg       0.98      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

LogisticRegression()

In [34]:
predicted = logr.predict([[4.6,2.8,5.6,1.4]])
print(predicted)

['Iris-virginica']


C:\Users\MGM\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [13]:
y_pred = logr.predict(X_test)
print(X_test,y_pred )

     SepalLength  SepalWidth  PetalLength  PetalWidth
57           4.9         2.4          3.3         1.0
65           6.7         3.1          4.4         1.4
31           5.4         3.4          1.5         0.4
89           5.5         2.5          4.0         1.3
22           4.6         3.6          1.0         0.2
130          7.4         2.8          6.1         1.9
113          5.7         2.5          5.0         2.0
86           6.7         3.1          4.7         1.5
134          6.1         2.6          5.6         1.4
116          6.5         3.0          5.5         1.8
128          6.4         2.8          5.6         2.1
147          6.5         3.0          5.2         2.0
69           5.6         2.5          3.9         1.1
58           6.6         2.9          4.6         1.3
138          6.0         3.0          4.8         1.8
16           5.4         3.9          1.3         0.4
106          4.9         2.5          4.5         1.7
70           5.9         3.2

In [35]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[22  0  0]
 [ 0 19  2]
 [ 0  1 16]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        22
Iris-versicolor       0.95      0.90      0.93        21
 Iris-virginica       0.89      0.94      0.91        17

       accuracy                           0.95        60
      macro avg       0.95      0.95      0.95        60
   weighted avg       0.95      0.95      0.95        60



In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

LogisticRegression()

In [32]:
predicted = logr.predict([[6.7,3.1,4.4,1.4]])
print(predicted)

['Iris-versicolor']


C:\Users\MGM\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [18]:
y_pred = logr.predict(X_test)
print(X_test,y_pred )

     SepalLength  SepalWidth  PetalLength  PetalWidth
23           5.1         3.3          1.7         0.5
41           4.5         2.3          1.3         0.3
65           6.7         3.1          4.4         1.4
37           4.9         3.1          1.5         0.1
20           5.4         3.4          1.7         0.2
18           5.7         3.8          1.7         0.3
13           4.3         3.0          1.1         0.1
40           5.0         3.5          1.3         0.3
84           5.4         3.0          4.5         1.5
134          6.1         2.6          5.6         1.4
120          6.9         3.2          5.7         2.3
125          7.2         3.2          6.0         1.8
32           5.2         4.1          1.5         0.1
19           5.1         3.8          1.5         0.3
21           5.1         3.7          1.5         0.4
68           6.2         2.2          4.5         1.5
145          6.7         3.0          5.2         2.3
81           5.5         2.4

In [19]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[23  0  0]
 [ 0 16  0]
 [ 0  0 14]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        23
Iris-versicolor       1.00      1.00      1.00        16
 Iris-virginica       1.00      1.00      1.00        14

       accuracy                           1.00        53
      macro avg       1.00      1.00      1.00        53
   weighted avg       1.00      1.00      1.00        53



In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

LogisticRegression()

In [31]:
predicted = logr.predict([[5.8,2.8,5.1,2.4]])
print(predicted)

['Iris-virginica']


C:\Users\MGM\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [24]:
y_pred = logr.predict(X_test)
print(X_test,y_pred )

     SepalLength  SepalWidth  PetalLength  PetalWidth
114          5.8         2.8          5.1         2.4
35           5.0         3.2          1.2         0.2
89           5.5         2.5          4.0         1.3
19           5.1         3.8          1.5         0.3
90           5.5         2.6          4.4         1.2
86           6.7         3.1          4.7         1.5
121          5.6         2.8          4.9         2.0
59           5.2         2.7          3.9         1.4
78           6.0         2.9          4.5         1.5
3            4.6         3.1          1.5         0.2
107          7.3         2.9          6.3         1.8
11           4.8         3.4          1.6         0.2
146          6.3         2.5          5.0         1.9
5            5.4         3.9          1.7         0.4
32           5.2         4.1          1.5         0.1
41           4.5         2.3          1.3         0.3
25           5.0         3.0          1.6         0.2
31           5.4         3.4

In [36]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[22  0  0]
 [ 0 19  2]
 [ 0  1 16]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        22
Iris-versicolor       0.95      0.90      0.93        21
 Iris-virginica       0.89      0.94      0.91        17

       accuracy                           0.95        60
      macro avg       0.95      0.95      0.95        60
   weighted avg       0.95      0.95      0.95        60

